version: '3.4'
services:
    mongodb:
        image: mongo:latest
        ports:
            - 27017:27017
    forecastaux:
        image: forecastaux
        build:
        context: .
        dockerfile: Dockerfile
        ports:
        - 5000:5000
            