version: '3'
services:
    mongodb:
        image: mongo:latest
        ports:
            - 27017:27017
    service:
        build: .
        depends_on: 
            - "mongodb"
        ports:
            - 5000:5000
            